# Chapter 2 — Linear Algebra
## Mathematics for Machine Learning (Deisenroth, Faisal & Ong)
### Complete Exercise Solutions (2.1 – 2.20)

> **Note on Source Material:**  
> All exercises and theoretical formulations in this notebook are taken directly from the textbook  
> **"Mathematics for Machine Learning"** by Marc Peter Deisenroth, A. Aldo Faisal, and Cheng Soon Ong (Cambridge University Press).


---


In [1]:
import numpy as np
from numpy.linalg import matrix_rank, inv, det, solve
import sympy as sp
from sympy import Matrix, symbols, Rational, sqrt, simplify, eye, zeros, oo
from sympy import init_printing
init_printing(use_unicode=True)
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)

---
## Exercise 2.1 — Abelian Group $(\mathbb{R}\setminus\{-1\}, \star)$

We consider $(\mathbb{R}\setminus\{-1\}, \star)$ with $a \star b := ab + a + b$.

**(a)** Show that $(\mathbb{R}\setminus\{-1\}, \star)$ is an Abelian group.

**(b)** Solve $3 \star x \star x = 15$.

### Solution 2.1

**Key observation:** $a \star b = ab + a + b = (1+a)(1+b) - 1$.

So if we let $\phi(a) = 1 + a$, then $\phi(a \star b) = (1+a)(1+b) = \phi(a) \cdot \phi(b)$.

This is an isomorphism to $(\mathbb{R}\setminus\{0\}, \cdot)$, which is a known Abelian group.

**(a)** We verify all group axioms:

1. **Closure:** For $a,b \in \mathbb{R}\setminus\{-1\}$: $a \star b = (1+a)(1+b) - 1$. Since $1+a \neq 0$ and $1+b \neq 0$, we have $(1+a)(1+b) \neq 0$, so $a \star b \neq -1$. ✓

2. **Associativity:** $(a \star b) \star c = ((1+a)(1+b)-1) \star c = (1+a)(1+b)(1+c) - 1 = a \star (b \star c)$. ✓

3. **Identity:** $e = 0$ since $a \star 0 = a \cdot 0 + a + 0 = a$. ✓

4. **Inverse:** $a^{-1} = \frac{-a}{1+a}$ since $a \star \frac{-a}{1+a} = (1+a)\frac{1}{1+a} - 1 = 0 = e$. ✓

5. **Commutativity:** $a \star b = ab + a + b = ba + b + a = b \star a$. ✓

**(b)** Using the isomorphism: $3 \star x \star x = 15 \implies (1+3)(1+x)^2 - 1 = 15 \implies 4(1+x)^2 = 16 \implies (1+x)^2 = 4 \implies x = 1 \text{ or } x = -3$.

In [2]:
# Verification of Exercise 2.1
def star(a, b):
    return a*b + a + b

# (a) Verify group axioms numerically
a, b, c = 2.5, 3.7, -0.5
print("=== Exercise 2.1 ===")
print(f"Associativity: (a⋆b)⋆c = {star(star(a,b), c):.6f}, a⋆(b⋆c) = {star(a, star(b,c)):.6f}")
print(f"Identity (e=0): a⋆0 = {star(a, 0)}, should be {a}")
a_inv = -a / (1 + a)
print(f"Inverse of {a}: {a_inv:.6f}, a⋆a⁻¹ = {star(a, a_inv):.6f} (should be 0)")
print(f"Commutativity: a⋆b = {star(a,b):.6f}, b⋆a = {star(b,a):.6f}")

# (b) Verify solutions
for x in [1, -3]:
    result = star(3, star(x, x))
    print(f"\n3⋆{x}⋆{x} = {result} (should be 15)")

=== Exercise 2.1 ===
Associativity: (a⋆b)⋆c = 7.225000, a⋆(b⋆c) = 7.225000
Identity (e=0): a⋆0 = 2.5, should be 2.5
Inverse of 2.5: -0.714286, a⋆a⁻¹ = -0.000000 (should be 0)
Commutativity: a⋆b = 15.450000, b⋆a = 15.450000

3⋆1⋆1 = 15 (should be 15)

3⋆-3⋆-3 = 15 (should be 15)


---
## Exercise 2.2 — Congruence Classes $\mathbb{Z}_n$

**(a)** Show that $(\mathbb{Z}_n, \oplus)$ is a group. Is it Abelian?

**(b)** For $n=5$: Draw the multiplication table of $\mathbb{Z}_5\setminus\{\bar{0}\}$ under $\otimes$. Show it's an Abelian group.

**(c)** Show $(\mathbb{Z}_8\setminus\{\bar{0}\}, \otimes)$ is NOT a group.

**(d)** $(\mathbb{Z}_n\setminus\{\bar{0}\}, \otimes)$ is a group iff $n$ is prime (Bézout's theorem).

### Solution 2.2

**(a)** $(\mathbb{Z}_n, \oplus)$ is a group:
- **Closure:** $(\bar{a} \oplus \bar{b}) = \overline{a+b} \in \mathbb{Z}_n$ ✓
- **Associativity:** Inherited from $(\mathbb{Z}, +)$ ✓
- **Identity:** $\bar{0}$ since $\bar{a} \oplus \bar{0} = \overline{a+0} = \bar{a}$ ✓
- **Inverse:** $\overline{n-a}$ since $\bar{a} \oplus \overline{n-a} = \overline{a + n - a} = \bar{n} = \bar{0}$ ✓
- **Abelian:** $\bar{a} \oplus \bar{b} = \overline{a+b} = \overline{b+a} = \bar{b} \oplus \bar{a}$ ✓

**(c)** In $\mathbb{Z}_8$: $\bar{2} \otimes \bar{4} = \overline{8} = \bar{0}$, so $\bar{2}$ has no inverse (it's a zero divisor). Not a group.

**(d)** By Bézout: $\gcd(a,n)=1 \iff \exists u,v: au + nv = 1 \implies \bar{a}\otimes\bar{u} = \bar{1}$. If $n$ is prime, every $a \in \{1,...,n-1\}$ satisfies $\gcd(a,n)=1$.

In [3]:
# (b) Multiplication table for Z5\{0}
print("=== Exercise 2.2(b): Multiplication table for Z₅\\{0} ===")
n = 5
elements = list(range(1, n))
print(f"\n  ⊗ | {' '.join(str(e) for e in elements)}")
print(f"----+{'---' * len(elements)}")
for a in elements:
    row = [(a * b) % n for b in elements]
    print(f"  {a} | {' '.join(str(r) for r in row)}")

# Verify closure (no zeros in table)
table = [[(a*b)%n for b in elements] for a in elements]
print(f"\nClosure: 0 appears in table? {any(0 in row for row in table)} (should be False)")

# Find inverses
print("\nInverses:")
for a in elements:
    for b in elements:
        if (a * b) % n == 1:
            print(f"  {a}⁻¹ = {b}")
            break

# (c) Z8\{0} is NOT a group
print("\n=== Exercise 2.2(c): Z₈\\{0} ===")
print(f"2 ⊗ 4 = {(2*4) % 8} (mod 8) → zero divisor! Not a group.")

# (d) Check for several n
print("\n=== Exercise 2.2(d): Group iff n is prime ===")
from math import gcd
for n in range(2, 13):
    is_group = all(gcd(a, n) == 1 for a in range(1, n))
    is_prime = all(n % i != 0 for i in range(2, n))
    print(f"  n={n:2d}: is_prime={is_prime}, (Z_n\\{{0}}, ⊗) is group={is_group} {'✓' if is_group == is_prime else '✗'}")

=== Exercise 2.2(b): Multiplication table for Z₅\{0} ===

  ⊗ | 1 2 3 4
----+------------
  1 | 1 2 3 4
  2 | 2 4 1 3
  3 | 3 1 4 2
  4 | 4 3 2 1

Closure: 0 appears in table? False (should be False)

Inverses:
  1⁻¹ = 1
  2⁻¹ = 3
  3⁻¹ = 2
  4⁻¹ = 4

=== Exercise 2.2(c): Z₈\{0} ===
2 ⊗ 4 = 0 (mod 8) → zero divisor! Not a group.

=== Exercise 2.2(d): Group iff n is prime ===
  n= 2: is_prime=True, (Z_n\{0}, ⊗) is group=True ✓
  n= 3: is_prime=True, (Z_n\{0}, ⊗) is group=True ✓
  n= 4: is_prime=False, (Z_n\{0}, ⊗) is group=False ✓
  n= 5: is_prime=True, (Z_n\{0}, ⊗) is group=True ✓
  n= 6: is_prime=False, (Z_n\{0}, ⊗) is group=False ✓
  n= 7: is_prime=True, (Z_n\{0}, ⊗) is group=True ✓
  n= 8: is_prime=False, (Z_n\{0}, ⊗) is group=False ✓
  n= 9: is_prime=False, (Z_n\{0}, ⊗) is group=False ✓
  n=10: is_prime=False, (Z_n\{0}, ⊗) is group=False ✓
  n=11: is_prime=True, (Z_n\{0}, ⊗) is group=True ✓
  n=12: is_prime=False, (Z_n\{0}, ⊗) is group=False ✓


---
## Exercise 2.3 — Heisenberg Group

Is $\left(G = \left\{\begin{bmatrix} 1 & x & z \\ 0 & 1 & y \\ 0 & 0 & 1 \end{bmatrix} : x,y,z \in \mathbb{R}\right\}, \cdot\right)$ a group? Abelian?

### Solution 2.3

Let $A(x_1,y_1,z_1)$ and $A(x_2,y_2,z_2)$ be elements of $G$.

**Closure:**
$$A(x_1,y_1,z_1) \cdot A(x_2,y_2,z_2) = \begin{bmatrix} 1 & x_1+x_2 & z_1+z_2+x_1 y_2 \\ 0 & 1 & y_1+y_2 \\ 0 & 0 & 1 \end{bmatrix} \in G \quad ✓$$

**Associativity:** Matrix multiplication is associative. ✓

**Identity:** $A(0,0,0) = I_3$ ✓

**Inverse:** $A(x,y,z)^{-1} = A(-x, -y, xy - z)$ ✓

**Not Abelian:** $A(1,0,0)\cdot A(0,1,0) = A(1,1,1)$ but $A(0,1,0)\cdot A(1,0,0) = A(1,1,0)$. ✗

$(G, \cdot)$ is a **non-Abelian group** (the Heisenberg group).

In [4]:
# Verification of Exercise 2.3
def heisenberg(x, y, z):
    return np.array([[1, x, z], [0, 1, y], [0, 0, 1]])

A1 = heisenberg(2, 3, 5)
A2 = heisenberg(-1, 4, 7)

print("=== Exercise 2.3 ===")
# Closure
prod = A1 @ A2
print(f"Product A1·A2:\n{prod}")
print(f"Lower-triangular with 1s on diagonal? {np.allclose(prod[1,0], 0) and np.allclose(prod[2,:2], [0,0]) and np.allclose(np.diag(prod), [1,1,1])}")

# Inverse
x, y, z = 2, 3, 5
A_inv = heisenberg(-x, -y, x*y - z)
print(f"\nA·A⁻¹:\n{A1 @ A_inv}")

# Non-commutativity
B1 = heisenberg(1, 0, 0)
B2 = heisenberg(0, 1, 0)
print(f"\nA(1,0,0)·A(0,1,0) =\n{B1 @ B2}")
print(f"A(0,1,0)·A(1,0,0) =\n{B2 @ B1}")
print(f"\nCommutative? {np.allclose(B1 @ B2, B2 @ B1)} → NOT Abelian")

=== Exercise 2.3 ===
Product A1·A2:
[[ 1  1 20]
 [ 0  1  7]
 [ 0  0  1]]
Lower-triangular with 1s on diagonal? True

A·A⁻¹:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

A(1,0,0)·A(0,1,0) =
[[1 1 1]
 [0 1 1]
 [0 0 1]]
A(0,1,0)·A(1,0,0) =
[[1 1 0]
 [0 1 1]
 [0 0 1]]

Commutative? False → NOT Abelian


---
## Exercise 2.4 — Matrix Products

Compute the following matrix products, if possible.

In [5]:
print("=== Exercise 2.4 ===")

# (a)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
print("(a) A·B =")
print(A @ B)

# (b)
print("\n(b) Same A, same B:")
print(A @ B)

# (c)
C = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n(c) C·D =")
print(C @ D)

# (d)
E = np.array([[1, 2, 1, -1, 2], [4, 1, -1, -4, -4]])
F = np.array([[0, 3], [1, -1], [2, 1], [5, 2]])
print(f"\n(d) E is {E.shape}, F is {F.shape}")
print("E·F =")
try:
    print(E @ F)
except ValueError as e:
    print(f"Cannot compute E·F: dimension mismatch (E is {E.shape}, F is {F.shape}). Product is undefined!")

# (e)
G = np.array([[0, 3], [1, -1], [2, 1], [5, 2]])
H = np.array([[1, 2, 1, -1], [4, 1, -1, -4]])
print(f"\n(e) G is {G.shape}, H is {H.shape}")
print("G·H =")
try:
    print(G @ H)
except ValueError as e:
    print(f"Cannot compute G·H: dimension mismatch (G is {G.shape}, H is {H.shape}). Product is undefined!")


=== Exercise 2.4 ===
(a) A·B =
[[ 4  3  5]
 [10  9 11]
 [16 15 17]]

(b) Same A, same B:
[[ 4  3  5]
 [10  9 11]
 [16 15 17]]

(c) C·D =
[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]

(d) E is (2, 5), F is (4, 2)
E·F =
Cannot compute E·F: dimension mismatch (E is (2, 5), F is (4, 2)). Product is undefined!

(e) G is (4, 2), H is (2, 4)
G·H =
[[ 12   3  -3 -12]
 [ -3   1   2   3]
 [  6   5   1  -6]
 [ 13  12   3 -13]]


---
## Exercise 2.5 — Systems of Linear Equations

Find all solutions of $Ax = b$.

In [6]:
print("=== Exercise 2.5 ===")

# (a)
print("--- Part (a) ---")
A_a = sp.Matrix([
    [1, 1, -1, -1, 0, -1],
    [2, 5, -7, 1, 0, -5],
    [2, -1, 1, -1, 0, 3],
    [5, 2, -4, 2, 0, 2]
])
b_a = sp.Matrix([1, -2, 4, 6])
Ab_a = A_a.row_join(b_a)
print("Augmented matrix [A|b]:")
sp.pprint(Ab_a)
print("\nRREF:")
rref, pivots = Ab_a.rref()
sp.pprint(rref)
print(f"Pivot columns: {pivots}")
print(f"Rank of A: {A_a.rank()}, free variables: {A_a.cols - A_a.rank()}")

# General solution
print("\nGeneral solution (using sympy linsolve):")
from sympy import linsolve
x1, x2, x3, x4, x5, x6 = sp.symbols('x1 x2 x3 x4 x5 x6')
sol_a = linsolve(Ab_a, x1, x2, x3, x4, x5, x6)
print(f"  x = {sol_a}")

=== Exercise 2.5 ===
--- Part (a) ---
Augmented matrix [A|b]:
⎡1  1   -1  -1  0  -1  1 ⎤
⎢                        ⎥
⎢2  5   -7  1   0  -5  -2⎥
⎢                        ⎥
⎢2  -1  1   -1  0  3   4 ⎥
⎢                        ⎥
⎣5  2   -4  2   0  2   6 ⎦

RREF:
⎡1  0  0  0  0  2/3    2 ⎤
⎢                        ⎥
⎢0  1  0  0  0  -8/3  3/2⎥
⎢                        ⎥
⎢0  0  1  0  0   -1    2 ⎥
⎢                        ⎥
⎣0  0  0  1  0   0    1/2⎦
Pivot columns: (0, 1, 2, 3)
Rank of A: 4, free variables: 2

General solution (using sympy linsolve):
  x = {(2 - 2*x6/3, 8*x6/3 + 3/2, x6 + 2, 1/2, x5, x6)}


In [7]:
# (b)
print("--- Part (b) ---")
A_b = sp.Matrix([
    [1, 0, 1],
    [1, -3, 0],
    [2, 1, -1],
    [-1, -2, -1]
])
b_b = sp.Matrix([3, 6, 5, -1])
Ab_b = A_b.row_join(b_b)
print("Augmented matrix [A|b]:")
sp.pprint(Ab_b)
rref_b, pivots_b = Ab_b.rref()
print("\nRREF:")
sp.pprint(rref_b)
print(f"Pivot columns: {pivots_b}")

sol_b = linsolve(Ab_b, x1, x2, x3)
print(f"\nSolution: x = {sol_b}")

--- Part (b) ---
Augmented matrix [A|b]:
⎡1   0   1   3 ⎤
⎢              ⎥
⎢1   -3  0   6 ⎥
⎢              ⎥
⎢2   1   -1  5 ⎥
⎢              ⎥
⎣-1  -2  -1  -1⎦

RREF:
⎡1  0  0  3 ⎤
⎢           ⎥
⎢0  1  0  -1⎥
⎢           ⎥
⎢0  0  1  0 ⎥
⎢           ⎥
⎣0  0  0  0 ⎦
Pivot columns: (0, 1, 2)

Solution: x = {(3, -1, 0)}


---
## Exercise 2.6 — Gaussian Elimination

Find all solutions of $Ax = b$ with the given $A$ and $b$.

In [8]:
print("=== Exercise 2.6 ===")
A6 = sp.Matrix([
    [0, 1, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 1]
])
b6 = sp.Matrix([2, -1, 1])
Ab6 = A6.row_join(b6)
print("Augmented [A|b]:")
sp.pprint(Ab6)

rref6, piv6 = Ab6.rref()
print("\nRREF:")
sp.pprint(rref6)
print(f"Pivot columns: {piv6}")

x1, x2, x3, x4, x5, x6 = sp.symbols('x1:7')
sol6 = linsolve(Ab6, x1, x2, x3, x4, x5, x6)
print(f"\nGeneral solution: {sol6}")

=== Exercise 2.6 ===
Augmented [A|b]:
⎡0  1  0  0  1  0  2 ⎤
⎢                    ⎥
⎢0  0  0  1  1  0  -1⎥
⎢                    ⎥
⎣0  1  0  0  0  1  1 ⎦

RREF:
⎡0  1  0  0  0  1   1 ⎤
⎢                     ⎥
⎢0  0  0  1  0  1   -2⎥
⎢                     ⎥
⎣0  0  0  0  1  -1  1 ⎦
Pivot columns: (1, 3, 4)

General solution: {(x1, 1 - x6, x3, -x6 - 2, x6 + 1, x6)}


---
## Exercise 2.7 — Eigenvalue Equation & Constraint

Find all $x \in \mathbb{R}^3$ such that $Ax = 12x$ and $\sum_{i} x_i = 1$.

In [9]:
print("=== Exercise 2.7 ===")
A7 = sp.Matrix([[6, 4, 3], [6, 0, 9], [0, 8, 0]])
print("A =")
sp.pprint(A7)

# Ax = 12x  →  (A - 12I)x = 0
A7_shifted = A7 - 12 * sp.eye(3)
print("\nA - 12I =")
sp.pprint(A7_shifted)

# Solve (A - 12I)x = 0
null = A7_shifted.nullspace()
print(f"\nNullspace of (A-12I): {null}")

if null:
    # The eigenvector is proportional to null[0]
    v = null[0]
    # Apply constraint sum(xi) = 1
    s = sum(v)
    x_sol = v / s
    print(f"\nEigenvector (normalized so sum=1):")
    sp.pprint(x_sol)
    
    # Verify
    print(f"\nVerification: Ax = {A7 * x_sol}")
    print(f"12x = {12 * x_sol}")
    print(f"sum(x) = {sum(x_sol)}")
else:
    print("12 is not an eigenvalue of A!")
    print("Eigenvalues of A:", A7.eigenvals())

=== Exercise 2.7 ===
A =
⎡6  4  3⎤
⎢       ⎥
⎢6  0  9⎥
⎢       ⎥
⎣0  8  0⎦

A - 12I =
⎡-6   4    3 ⎤
⎢            ⎥
⎢6   -12   9 ⎥
⎢            ⎥
⎣0    8   -12⎦

Nullspace of (A-12I): [Matrix([
[3/2],
[3/2],
[  1]])]

Eigenvector (normalized so sum=1):
⎡3/8⎤
⎢   ⎥
⎢3/8⎥
⎢   ⎥
⎣1/4⎦

Verification: Ax = Matrix([[9/2], [9/2], [3]])
12x = Matrix([[9/2], [9/2], [3]])
sum(x) = 1


---
## Exercise 2.8 — Matrix Inverses

In [10]:
print("=== Exercise 2.8 ===")

# (a)
A8a = sp.Matrix([[2, 3, 4], [3, 4, 5], [4, 5, 6]])
print("(a) A =")
sp.pprint(A8a)
print(f"det(A) = {A8a.det()}")
if A8a.det() != 0:
    print("A⁻¹ =")
    sp.pprint(A8a.inv())
else:
    print("A is singular — NOT invertible!")

# (b)
print("\n(b) A =")
A8b = sp.Matrix([[1, 0, 1, 0], [0, 1, 1, 0], [1, 1, 0, 1], [1, 1, 1, 0]])
sp.pprint(A8b)
print(f"det(A) = {A8b.det()}")
if A8b.det() != 0:
    print("A⁻¹ =")
    sp.pprint(A8b.inv())
    print("\nVerification A·A⁻¹ = I:")
    sp.pprint(A8b * A8b.inv())
else:
    print("A is singular — NOT invertible!")

=== Exercise 2.8 ===
(a) A =
⎡2  3  4⎤
⎢       ⎥
⎢3  4  5⎥
⎢       ⎥
⎣4  5  6⎦
det(A) = 0
A is singular — NOT invertible!

(b) A =
⎡1  0  1  0⎤
⎢          ⎥
⎢0  1  1  0⎥
⎢          ⎥
⎢1  1  0  1⎥
⎢          ⎥
⎣1  1  1  0⎦
det(A) = 1
A⁻¹ =
⎡0   -1  0  1 ⎤
⎢             ⎥
⎢-1  0   0  1 ⎥
⎢             ⎥
⎢1   1   0  -1⎥
⎢             ⎥
⎣1   1   1  -2⎦

Verification A·A⁻¹ = I:
⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦


---
## Exercise 2.9 — Subspaces of $\mathbb{R}^3$

Which of the following sets are subspaces of $\mathbb{R}^3$?

### Solution 2.9

**(a)** $A = \{(\lambda, \lambda + \mu^3, \lambda - \mu^3) \mid \lambda, \mu \in \mathbb{R}\}$

**Not a subspace.** Closure under addition fails. Take $\lambda_1=0, \mu_1=1$ giving $(0, 1, -1)$ and $\lambda_2=0, \mu_2=1$ giving $(0, 1, -1)$. Sum is $(0, 2, -2)$. For this to be in $A$: $\lambda = 0$, $\mu^3 = 2 \implies \mu = \sqrt[3]{2}$, and $-\mu^3 = -2$. ✓ this works. But take $\lambda=0, \mu=1$: $(0,1,-1)$ and $\lambda=0, \mu=2$: $(0,8,-8)$. Sum: $(0,9,-9)$. Need $\mu^3=9$, $\lambda=0$ ✓. Actually, let's check scalar multiplication: $2 \cdot (0,1,-1) = (0,2,-2)$, need $\lambda=0, \mu^3=2$. ✓

Actually, $A = \{(\lambda, \lambda+t, \lambda-t) \mid \lambda \in \mathbb{R}, t \in \mathbb{R}\}$ where $t = \mu^3$ ranges over all of $\mathbb{R}$. So $A = \text{span}\{(1,1,1), (0,1,-1)\}$, which **is a subspace**. ✓

**(b)** $B = \{(\lambda^2, -\lambda^2, 0) \mid \lambda \in \mathbb{R}\}$

**Not a subspace.** $(1,-1,0) \in B$ (take $\lambda=1$), but $(-1)(1,-1,0) = (-1,1,0)$. For $(-1,1,0) \in B$: need $\lambda^2 = -1$, impossible. ✗

**(c)** $C = \{(\xi_1, \xi_2, \xi_3) \in \mathbb{R}^3 \mid \xi_1 - 2\xi_2 + 3\xi_3 = \gamma\}$

- If $\gamma = 0$: **Subspace** (solution set of homogeneous equation). ✓
- If $\gamma \neq 0$: **Not a subspace** ($0 \notin C$). ✗

**(d)** $D = \{(\xi_1, \xi_2, \xi_3) \in \mathbb{R}^3 \mid \xi_2 \in \mathbb{Z}\}$

**Not a subspace.** $(0,1,0) \in D$ but $\frac{1}{2}(0,1,0) = (0, 0.5, 0) \notin D$. ✗

In [11]:
print("=== Exercise 2.9 — Summary ===")
print("(a) A: YES — subspace (span of (1,1,1) and (0,1,-1))")
print("(b) B: NO  — not closed under scalar multiplication")
print("(c) C: YES iff γ=0, NO otherwise")
print("(d) D: NO  — not closed under scalar multiplication")

=== Exercise 2.9 — Summary ===
(a) A: YES — subspace (span of (1,1,1) and (0,1,-1))
(b) B: NO  — not closed under scalar multiplication
(c) C: YES iff γ=0, NO otherwise
(d) D: NO  — not closed under scalar multiplication


---
## Exercise 2.10 — Linear Independence

In [12]:
print("=== Exercise 2.10 ===")

# (a)
print("--- Part (a) ---")
X_a = sp.Matrix([[2, 1, 3], [-1, 1, -3], [3, -2, 8]])
print("Matrix with x1, x2, x3 as columns:")
sp.pprint(X_a.T)  # show column vectors as rows for readability
rref_a, piv_a = X_a.rref()
print(f"RREF pivot columns: {piv_a}")
print(f"Rank: {X_a.rank()}, Num vectors: {X_a.cols}")
print(f"Linearly independent? {X_a.rank() == X_a.cols}")
if X_a.rank() < X_a.cols:
    print("Dependence relation (nullspace):")
    for v in X_a.nullspace():
        sp.pprint(v.T)

# (b)
print("\n--- Part (b) ---")
X_b = sp.Matrix([
    [1, 1, 1],
    [2, 1, 0],
    [1, 0, 0],
    [0, 1, 1],
    [0, 1, 1]
])
print(f"Rank: {X_b.rank()}, Num vectors: {X_b.cols}")
print(f"Linearly independent? {X_b.rank() == X_b.cols}")

=== Exercise 2.10 ===
--- Part (a) ---
Matrix with x1, x2, x3 as columns:
⎡2  -1  3 ⎤
⎢         ⎥
⎢1  1   -2⎥
⎢         ⎥
⎣3  -3  8 ⎦
RREF pivot columns: (0, 1)
Rank: 2, Num vectors: 3
Linearly independent? False
Dependence relation (nullspace):
[-2  1  1]

--- Part (b) ---
Rank: 3, Num vectors: 3
Linearly independent? True


---
## Exercise 2.11 — Linear Combination

Write $y = \begin{bmatrix}1\\-2\\5\end{bmatrix}$ as a linear combination of $x_1, x_2, x_3$.

In [13]:
print("=== Exercise 2.11 ===")
X_11 = sp.Matrix([[1, 1, 2], [1, 2, -1], [1, 3, 1]])
y_11 = sp.Matrix([1, -2, 5])

# Solve X·c = y for coefficients c
c = X_11.solve(y_11)
print("Coefficients [λ1, λ2, λ3]:")
sp.pprint(c)
print(f"\nVerification: λ1·x1 + λ2·x2 + λ3·x3 = {X_11 * c} (should be {y_11.T})")

=== Exercise 2.11 ===
Coefficients [λ1, λ2, λ3]:
⎡-6⎤
⎢  ⎥
⎢3 ⎥
⎢  ⎥
⎣2 ⎦

Verification: λ1·x1 + λ2·x2 + λ3·x3 = Matrix([[1], [-2], [5]]) (should be Matrix([[1, -2, 5]]))


---
## Exercise 2.12 — Basis of Intersection $U_1 \cap U_2$

In [14]:
print("=== Exercise 2.12 ===")
# U1 = span of columns of A1, U2 = span of columns of A2
A1 = sp.Matrix([[1, 2, -1], [1, -1, 1], [-3, 0, -1], [1, -1, 0]])
A2 = sp.Matrix([[-1, 2, -3], [-2, -2, 6], [2, 0, -2], [1, 1, -1]])

print("U1 generators (columns of A1):")
sp.pprint(A1)
print(f"dim(U1) = rank(A1) = {A1.rank()}")

print("\nU2 generators (columns of A2):")
sp.pprint(A2)
print(f"dim(U2) = rank(A2) = {A2.rank()}")

# U1 ∩ U2: vectors that are in both spans
# x ∈ U1 ∩ U2  ⟺  A1·α = A2·β  ⟺  [A1 | -A2]·[α; β] = 0
M = A1.row_join(-A2)
print("\n[A1 | -A2]:")
sp.pprint(M)

ns = M.nullspace()
print(f"\nNullspace dimension: {len(ns)}")

# Extract intersection basis: for each nullspace vector [α; β], compute A1·α
intersection_basis = []
for v in ns:
    alpha = v[:A1.cols, :]
    vec = A1 * alpha
    intersection_basis.append(vec)

print("\nBasis for U1 ∩ U2:")
for v in intersection_basis:
    sp.pprint(v.T)

=== Exercise 2.12 ===
U1 generators (columns of A1):
⎡1   2   -1⎤
⎢          ⎥
⎢1   -1  1 ⎥
⎢          ⎥
⎢-3  0   -1⎥
⎢          ⎥
⎣1   -1  0 ⎦
dim(U1) = rank(A1) = 3

U2 generators (columns of A2):
⎡-1  2   -3⎤
⎢          ⎥
⎢-2  -2  6 ⎥
⎢          ⎥
⎢2   0   -2⎥
⎢          ⎥
⎣1   1   -1⎦
dim(U2) = rank(A2) = 3

[A1 | -A2]:
⎡1   2   -1  1   -2  3 ⎤
⎢                      ⎥
⎢1   -1  1   2   2   -6⎥
⎢                      ⎥
⎢-3  0   -1  -2  0   2 ⎥
⎢                      ⎥
⎣1   -1  0   -1  -1  1 ⎦

Nullspace dimension: 2

Basis for U1 ∩ U2:
[8/3  -2/3  -4/3  1/3]
[-16/3  4/3  8/3  4/3]


---
## Exercise 2.13 — Solution Spaces Intersection

$U_1$ is the solution space of $A_1 x = 0$ and $U_2$ is the solution space of $A_2 x = 0$.

In [15]:
print("=== Exercise 2.13 ===")
A1_13 = sp.Matrix([[1, 0, 1], [1, -2, -1], [2, 1, 3], [1, 0, 1]])
A2_13 = sp.Matrix([[3, -3, 0], [1, 2, 3], [7, -5, 2], [-1, 3, 2]])

# (a) Dimensions
r1, r2 = A1_13.rank(), A2_13.rank()
n = A1_13.cols
print(f"(a) dim(U1) = {n} - rank(A1) = {n} - {r1} = {n - r1}")
print(f"    dim(U2) = {n} - rank(A2) = {n} - {r2} = {n - r2}")

# (b) Bases
print("\n(b) Basis of U1 (nullspace of A1):")
for v in A1_13.nullspace():
    sp.pprint(v.T)

print("Basis of U2 (nullspace of A2):")
for v in A2_13.nullspace():
    sp.pprint(v.T)

# (c) U1 ∩ U2 = nullspace of [A1; A2] (stacked)
print("\n(c) Basis of U1 ∩ U2:")
A_stacked = A1_13.col_join(A2_13)
ns_int = A_stacked.nullspace()
if ns_int:
    for v in ns_int:
        sp.pprint(v.T)
else:
    print("U1 ∩ U2 = {0}")

=== Exercise 2.13 ===
(a) dim(U1) = 3 - rank(A1) = 3 - 2 = 1
    dim(U2) = 3 - rank(A2) = 3 - 2 = 1

(b) Basis of U1 (nullspace of A1):
[-1  -1  1]
Basis of U2 (nullspace of A2):
[-1  -1  1]

(c) Basis of U1 ∩ U2:
[-1  -1  1]


---
## Exercise 2.14 — Column Spaces Intersection

$U_1$ is spanned by columns of $A_1$, $U_2$ by columns of $A_2$ (same matrices as 2.13).

In [16]:
print("=== Exercise 2.14 ===")
# Same A1, A2 as Ex 2.13, but now U1 = col(A1), U2 = col(A2)

# (a) Dimensions = rank of each matrix
print(f"(a) dim(U1) = rank(A1) = {A1_13.rank()}")
print(f"    dim(U2) = rank(A2) = {A2_13.rank()}")

# (b) Bases
print("\n(b) Basis of U1 (column space of A1):")
for v in A1_13.columnspace():
    sp.pprint(v.T)

print("Basis of U2 (column space of A2):")
for v in A2_13.columnspace():
    sp.pprint(v.T)

# (c) U1 ∩ U2: same stacking trick as Ex 2.12
print("\n(c) Basis of U1 ∩ U2:")
M_14 = A1_13.row_join(-A2_13)
ns_14 = M_14.nullspace()
intersection_basis_14 = []
for v in ns_14:
    alpha = v[:A1_13.cols, :]
    vec = A1_13 * alpha
    intersection_basis_14.append(vec)

if intersection_basis_14:
    for v in intersection_basis_14:
        sp.pprint(v.T)
else:
    print("U1 ∩ U2 = {0}")

=== Exercise 2.14 ===
(a) dim(U1) = rank(A1) = 2
    dim(U2) = rank(A2) = 2

(b) Basis of U1 (column space of A1):
[1  1  2  1]
[0  -2  1  0]
Basis of U2 (column space of A2):
[3  1  7  -1]
[-3  2  -5  3]

(c) Basis of U1 ∩ U2:
[0  0  0  0]
[0  0  0  0]


---
## Exercise 2.15 — Subspace Intersection $F \cap G$

In [17]:
print("=== Exercise 2.15 ===")
print("F = {(x,y,z) ∈ ℝ³ | x + y - z = 0}")
print("G = {(a-b, a+b, a-3b) | a,b ∈ ℝ}")

# (a) Show F and G are subspaces
print("\n(a) F is the kernel of [1, 1, -1] → subspace ✓")
print("    G = span{(1,1,1), (-1,1,-3)} → subspace ✓")

# (b) F ∩ G without basis vectors
# (x,y,z) ∈ G means x=a-b, y=a+b, z=a-3b
# (x,y,z) ∈ F means x+y-z = 0
# Substituting: (a-b)+(a+b)-(a-3b) = a+3b = 0 → a = -3b
# So x = -3b-b = -4b, y = -3b+b = -2b, z = -3b-3b = -6b
print("\n(b) Substituting G into F's equation:")
print("    (a-b)+(a+b)-(a-3b) = a + 3b = 0 → a = -3b")
print("    F ∩ G = {(-4b, -2b, -6b) | b ∈ ℝ} = span{(-4, -2, -6)} = span{(2, 1, 3)}")

# (c) Using basis vectors
print("\n(c) Verification using basis computation:")
# F: kernel of [1, 1, -1]
F_eq = sp.Matrix([[1, 1, -1]])
F_basis = F_eq.nullspace()
print("Basis of F:")
for v in F_basis:
    sp.pprint(v.T)

# G = span{(1,1,1), (-1,1,-3)}
G_gens = sp.Matrix([[1, -1], [1, 1], [1, -3]])
print("Generators of G: (1,1,1) and (-1,1,-3)")

# F ∩ G: solve [G_gens | -F_basis_matrix] · params = 0
F_mat = sp.Matrix.hstack(*F_basis)  # columns
M_15 = G_gens.row_join(-F_mat)
ns_15 = M_15.nullspace()
print("\nBasis of F ∩ G:")
for v in ns_15:
    vec = G_gens * v[:2, :]
    sp.pprint(vec.T)

=== Exercise 2.15 ===
F = {(x,y,z) ∈ ℝ³ | x + y - z = 0}
G = {(a-b, a+b, a-3b) | a,b ∈ ℝ}

(a) F is the kernel of [1, 1, -1] → subspace ✓
    G = span{(1,1,1), (-1,1,-3)} → subspace ✓

(b) Substituting G into F's equation:
    (a-b)+(a+b)-(a-3b) = a + 3b = 0 → a = -3b
    F ∩ G = {(-4b, -2b, -6b) | b ∈ ℝ} = span{(-4, -2, -6)} = span{(2, 1, 3)}

(c) Verification using basis computation:
Basis of F:
[-1  1  0]
[1  0  1]
Generators of G: (1,1,1) and (-1,1,-3)

Basis of F ∩ G:
[2/3  1/3  1]


---
## Exercise 2.16 — Linear Mappings

Are the following mappings linear?

### Solution 2.16

**(a)** $\Phi(f) = \int_a^b f(x)\,dx$ — **Linear** ✓
- $\Phi(f+g) = \int(f+g) = \int f + \int g = \Phi(f) + \Phi(g)$
- $\Phi(\alpha f) = \int \alpha f = \alpha \int f = \alpha\Phi(f)$

**(b)** $\Phi(f) = f'$ (differentiation) — **Linear** ✓
- $(f+g)' = f' + g'$
- $(\alpha f)' = \alpha f'$

**(c)** $\Phi(x) = \cos(x)$ — **Not linear** ✗
- $\cos(x+y) \neq \cos(x) + \cos(y)$ in general
- Counter-example: $\cos(0) = 1 \neq 0$, but $\Phi(0) = 0$ is required for linear maps.

**(d)** $\Phi(x) = \begin{pmatrix} 1 & 2 & 3 \\ 1 & 4 & 3 \end{pmatrix} x$ — **Linear** ✓
- Matrix-vector multiplication is always linear.

**(e)** $\Phi(x) = \begin{pmatrix} \cos\theta & \sin\theta \\ -\sin\theta & \cos\theta \end{pmatrix} x$ — **Linear** ✓
- Matrix multiplication = linear mapping (rotation matrix).

In [18]:
print("=== Exercise 2.16 — Summary ===")
print("(a) Integration:      LINEAR  ✓")
print("(b) Differentiation:  LINEAR  ✓")
print("(c) cos(x):           NOT linear ✗ (cos(0) = 1 ≠ 0)")
print("(d) Matrix multiply:  LINEAR  ✓")
print("(e) Rotation matrix:  LINEAR  ✓")

# Verify (c)
print(f"\nVerification (c): cos(0) = {np.cos(0)} ≠ 0, so Φ(0) ≠ 0 → not linear")
print(f"Also: cos(π/4 + π/4) = {np.cos(np.pi/4 + np.pi/4):.4f}")
print(f"  but cos(π/4) + cos(π/4) = {np.cos(np.pi/4) + np.cos(np.pi/4):.4f}")

=== Exercise 2.16 — Summary ===
(a) Integration:      LINEAR  ✓
(b) Differentiation:  LINEAR  ✓
(c) cos(x):           NOT linear ✗ (cos(0) = 1 ≠ 0)
(d) Matrix multiply:  LINEAR  ✓
(e) Rotation matrix:  LINEAR  ✓

Verification (c): cos(0) = 1.0 ≠ 0, so Φ(0) ≠ 0 → not linear
Also: cos(π/4 + π/4) = 0.0000
  but cos(π/4) + cos(π/4) = 1.4142


---
## Exercise 2.17 — Transformation Matrix, Rank, Kernel, Image

In [19]:
print("=== Exercise 2.17 ===")
# Φ: R³ → R⁴, Φ(x) = [3x1+2x2+x3, x1+x2+x3, x1-3x2, 2x1+3x2+x3]

A_phi = sp.Matrix([
    [3, 2, 1],
    [1, 1, 1],
    [1, -3, 0],
    [2, 3, 1]
])

print("Transformation matrix A_Φ:")
sp.pprint(A_phi)
print(f"\nrk(A_Φ) = {A_phi.rank()}")

# Kernel
ker = A_phi.nullspace()
print(f"\nKernel (nullspace):")
if ker:
    for v in ker:
        sp.pprint(v.T)
else:
    print("  ker(Φ) = {0}")
print(f"dim(ker(Φ)) = {len(ker)}")

# Image
img = A_phi.columnspace()
print(f"\nImage (column space):")
for v in img:
    sp.pprint(v.T)
print(f"dim(Im(Φ)) = {len(img)}")

# Verify rank-nullity
print(f"\nRank-Nullity: dim(ker) + dim(Im) = {len(ker)} + {len(img)} = {len(ker)+len(img)} = dim(domain) = {A_phi.cols} ✓")

=== Exercise 2.17 ===
Transformation matrix A_Φ:
⎡3  2   1⎤
⎢        ⎥
⎢1  1   1⎥
⎢        ⎥
⎢1  -3  0⎥
⎢        ⎥
⎣2  3   1⎦

rk(A_Φ) = 3

Kernel (nullspace):
  ker(Φ) = {0}
dim(ker(Φ)) = 0

Image (column space):
[3  1  1  2]
[2  1  -3  3]
[1  1  0  1]
dim(Im(Φ)) = 3

Rank-Nullity: dim(ker) + dim(Im) = 0 + 3 = 3 = dim(domain) = 3 ✓


---
## Exercise 2.18 — Kernel and Image of Composed Automorphisms

Let $f \circ g = \text{id}_E$. Show:
1. $\ker(f) = \ker(g \circ f)$
2. $\text{Im}(g) = \text{Im}(g \circ f)$
3. $\ker(f) \cap \text{Im}(g) = \{0_E\}$

### Solution 2.18

Given: $f \circ g = \text{id}_E$.

**1. $\ker(f) = \ker(g \circ f)$:**

- ($\subseteq$): If $x \in \ker(f)$, then $f(x) = 0$, so $(g \circ f)(x) = g(f(x)) = g(0) = 0$, hence $x \in \ker(g \circ f)$.
- ($\supseteq$): If $x \in \ker(g \circ f)$, then $g(f(x)) = 0$. Apply $f$: $f(g(f(x))) = f(0) = 0$. But $f \circ g = \text{id}$, so $f(g(f(x))) = f(x)$. Thus $f(x) = 0$, i.e., $x \in \ker(f)$.

**2. $\text{Im}(g) = \text{Im}(g \circ f)$:**

- ($\supseteq$): $\text{Im}(g \circ f) \subseteq \text{Im}(g)$ trivially (since $g \circ f(x) = g(f(x)) \in \text{Im}(g)$).
- ($\subseteq$): Let $y \in \text{Im}(g)$. Then $y = g(z)$ for some $z$. Since $f \circ g = \text{id}$, we have $f(g(z)) = z$. So $y = g(z) = g(f(g(z))) = (g \circ f)(g(z)) \in \text{Im}(g \circ f)$.

**3. $\ker(f) \cap \text{Im}(g) = \{0_E\}$:**

Let $x \in \ker(f) \cap \text{Im}(g)$. Then $f(x) = 0$ and $x = g(z)$ for some $z$.
So $0 = f(x) = f(g(z)) = z$ (since $f \circ g = \text{id}$). Thus $x = g(0) = 0$. ∎

In [20]:
# Numerical verification with concrete matrices
print("=== Exercise 2.18 — Numerical Verification ===")
# f ∘ g = id, so f = g⁻¹ on Im(g)
# Let's use f as a 3×3 matrix F and g = right-inverse
# For square invertible matrices: F·G = I means G = F⁻¹
F = sp.Matrix([[1, 2, 0], [0, 1, 1], [1, 0, 1]])
G = F.inv()
print(f"F·G = I: {F * G == sp.eye(3)}")
print(f"ker(F) = {F.nullspace()} (trivial for invertible)")
print(f"ker(G∘F) = {(G*F).nullspace()} (G·F = I, so trivial)")
print("Properties verified for invertible case (all trivial).")

# For non-square case (more interesting)
print("\nNon-square case: E = ℝ³, F: ℝ³→ℝ², G: ℝ²→ℝ³")
F2 = sp.Matrix([[1, 0, 0], [0, 1, 0]])  # projection
G2 = sp.Matrix([[1, 0], [0, 1], [0, 0]])  # embedding
print(f"F·G = {F2 * G2} = I₂ ✓")
print(f"ker(F) = {[v.T for v in F2.nullspace()]}")
print(f"ker(G∘F) = {[v.T for v in (G2*F2).nullspace()]}")
print(f"Im(G) = {[v.T for v in G2.columnspace()]}")
print(f"Im(G∘F) = {[v.T for v in (G2*F2).columnspace()]}")

=== Exercise 2.18 — Numerical Verification ===
F·G = I: True
ker(F) = [] (trivial for invertible)
ker(G∘F) = [] (G·F = I, so trivial)
Properties verified for invertible case (all trivial).

Non-square case: E = ℝ³, F: ℝ³→ℝ², G: ℝ²→ℝ³
F·G = Matrix([[1, 0], [0, 1]]) = I₂ ✓
ker(F) = [Matrix([[0, 0, 1]])]
ker(G∘F) = [Matrix([[0, 0, 1]])]
Im(G) = [Matrix([[1, 0, 0]]), Matrix([[0, 1, 0]])]
Im(G∘F) = [Matrix([[1, 0, 0]]), Matrix([[0, 1, 0]])]


---
## Exercise 2.19 — Kernel, Image, and Basis Change

In [21]:
print("=== Exercise 2.19 ===")
A_19 = sp.Matrix([[1, 1, 0], [1, -1, 0], [1, 1, 1]])
print("A_Φ (standard basis):")
sp.pprint(A_19)

# (a) ker(Φ) and Im(Φ)
print("\n(a) ker(Φ):")
ker_19 = A_19.nullspace()
if ker_19:
    for v in ker_19:
        sp.pprint(v.T)
else:
    print("  ker(Φ) = {0}")

print("\nIm(Φ):")
for v in A_19.columnspace():
    sp.pprint(v.T)
print(f"dim(Im(Φ)) = {len(A_19.columnspace())}")

# (b) Basis change to B = {b1, b2, b3}
print("\n(b) Basis change:")
B = sp.Matrix([[1, 1, 1], [1, 2, 0], [1, 1, 0]])
print("B (new basis as columns):")
sp.pprint(B)

# Ã = B⁻¹ · A · B
A_tilde = B.inv() * A_19 * B
print("\nÃ_Φ = B⁻¹ · A_Φ · B:")
sp.pprint(A_tilde)

# Verify: A_Φ · b_i should map to same as B · Ã · e_i
print("\nVerification:")
for i in range(3):
    e_i = sp.zeros(3, 1)
    e_i[i] = 1
    lhs = A_19 * B[:, i]
    rhs = B * A_tilde * e_i
    print(f"  A·b{i+1} = {lhs.T},  B·Ã·e{i+1} = {rhs.T}, match: {lhs == rhs}")

=== Exercise 2.19 ===
A_Φ (standard basis):
⎡1  1   0⎤
⎢        ⎥
⎢1  -1  0⎥
⎢        ⎥
⎣1  1   1⎦

(a) ker(Φ):
  ker(Φ) = {0}

Im(Φ):
[1  1  1]
[1  -1  1]
[0  0  1]
dim(Im(Φ)) = 3

(b) Basis change:
B (new basis as columns):
⎡1  1  1⎤
⎢       ⎥
⎢1  2  0⎥
⎢       ⎥
⎣1  1  0⎦

Ã_Φ = B⁻¹ · A_Φ · B:
⎡6   9   1⎤
⎢         ⎥
⎢-3  -5  0⎥
⎢         ⎥
⎣-1  -1  0⎦

Verification:
  A·b1 = Matrix([[2, 0, 3]]),  B·Ã·e1 = Matrix([[2, 0, 3]]), match: True
  A·b2 = Matrix([[3, -1, 4]]),  B·Ã·e2 = Matrix([[3, -1, 4]]), match: True
  A·b3 = Matrix([[1, 1, 1]]),  B·Ã·e3 = Matrix([[1, 1, 1]]), match: True


---
## Exercise 2.20 — Basis Change in $\mathbb{R}^2$

In [22]:
print("=== Exercise 2.20 ===")
# b1, b2 expressed in standard basis
b1 = sp.Matrix([2, 1])
b2 = sp.Matrix([-1, -1])

# b1', b2' expressed in standard basis  
b1p = sp.Matrix([2, -2])
b2p = sp.Matrix([1, 1])

# B = [b1 | b2], B' = [b1' | b2']
B_old = sp.Matrix([[2, -1], [1, -1]])
B_new = sp.Matrix([[2, 1], [-2, 1]])

print("Old basis B:")
sp.pprint(B_old)
print("\nNew basis B':")
sp.pprint(B_new)

# Linear mapping Φ given in B coordinates:
# Φ(b1) = b1 - b2 and Φ(b2) = b1 + b2 (in old basis)
# So the matrix w.r.t. B is:
A_B = sp.Matrix([[1, 1], [-1, 1]])  # columns = images of basis vectors
print("\nA_Φ w.r.t. old basis B:")
sp.pprint(A_B)

# Transformation matrix w.r.t. standard basis:
A_std = B_old * A_B * B_old.inv()
print("\nA_Φ w.r.t. standard basis:")
sp.pprint(A_std)

# Transformation matrix w.r.t. new basis B':
A_Bp = B_new.inv() * A_std * B_new
# Or equivalently: A_Bp = B_new.inv() * B_old * A_B * B_old.inv() * B_new
print("\nA_Φ w.r.t. new basis B':")
sp.pprint(A_Bp)

# The change of basis matrix S from B to B'
S = B_new.inv() * B_old
print("\nChange of basis matrix S = (B')⁻¹ B:")
sp.pprint(S)
print(f"\nVerification: S⁻¹ · A_B · S = A_B'?")
sp.pprint(S.inv() * A_B * S)

=== Exercise 2.20 ===
Old basis B:
⎡2  -1⎤
⎢     ⎥
⎣1  -1⎦

New basis B':
⎡2   1⎤
⎢     ⎥
⎣-2  1⎦

A_Φ w.r.t. old basis B:
⎡1   1⎤
⎢     ⎥
⎣-1  1⎦

A_Φ w.r.t. standard basis:
⎡4  -5⎤
⎢     ⎥
⎣2  -2⎦

A_Φ w.r.t. new basis B':
⎡5/2  -1/4⎤
⎢         ⎥
⎣13   -1/2⎦

Change of basis matrix S = (B')⁻¹ B:
⎡1/4  0 ⎤
⎢       ⎥
⎣3/2  -1⎦

Verification: S⁻¹ · A_B · S = A_B'?
⎡ 7    -4⎤
⎢        ⎥
⎣37/4  -5⎦
